### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zymiboxpay** [yiyizym/yiyizym.github.io#2]
# sinatra 源码系列
## <del>0.1.0</del>
- <del>loader.rb Set</del>
- <del>kernel.rb</del>
- <del>Object / Module / Class / Kernel  祖先链</del>
- <del>[metaid.rb](http://viewsourcecode.org/why/hacking/seeingMetaclassesClearly.html)</del>
- <del>symbol.rb to_proc __send__</del>
- <del>module.rb</del>
- <del>request_method PUT/PATH/DELETE -> POST</del>
- <del>Sinatra::Environment.prepare</del>
- <del>OptionParser</del>
- <del>ARGV</del>
- <del>options.rb</del>
- <del>logger.rb</del>
- <del>irb.rb</del>
- <del>server.rb</del>
- <del>dispatcher.rb</del>
- <del>sessions.rb</del>
- <del>event.rb</del>
- <del>renderer.rb</del>
- <del>dsl.rb</del>
- <del>test 测试</del>
# 算法系列
- <del>插入排序</del>
- <del>希尔排序</del>
- <del>归并排序</del>
- <del>堆排序</del>
# Rails 5 API
- <del>玩玩 ActionCable</del>
# 博客改版
- <del>整改首页</del>
# 感想系列
- 无聊就看源码/写基础算法

**Comment by yiyizym** [comment]
给自己挖了个大坑

**Comment by yiyizym** [comment]
0.1.0 这个坑不间断填了 17 天
